extends Node

class_name LevelLoader

const Platform = preload("res://entities/platforms/DestructableGemsPlatform.tscn")

static func loadFromFile(filePath: String) -> void:
	pass

static func load(data, stage: int, level: int) -> Array:
	return _load(data, stage, level)

static func _load(data, stage: int, level: int) -> Array:
	match level % 4:
		0:
			return _load_0_0()
		1: 
			return _load_0_1()
		2:
			return _load_0_2()
		3:
			return _load_0_3()
		_:
			return _load_0_0()

static func _load_0_0() -> Array:
	var platforms = []
	var platform = Platform.instance()
	platform.changeGemType(0)
	platform.set_stage_and_level(0,0)
	platforms.append({ "position": Vector2(350.0, 1200.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(0)
	platform.set_stage_and_level(0,0)
	platforms.append({ "position": Vector2(200.0, 1000.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(0)
	platform.set_stage_and_level(0,0)
	platforms.append({ "position": Vector2(300.0, 730.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(0)
	platform.set_stage_and_level(0,0)
	platforms.append({ "position": Vector2(120.0, 520.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(0)
	platform.set_stage_and_level(0,0)
	platforms.append({ "position": Vector2(480.0, 400.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(0)
	platform.set_stage_and_level(0,0)
	platforms.append({ "position": Vector2(90.0, 200.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(0)
	platform.set_stage_and_level(0,0)
	platforms.append({ "position": Vector2(690.0, 105.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(0)
	platform.set_stage_and_level(0,0)
	platforms.append({ "position": Vector2(90.0, -99.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(0)
	platform.set_stage_and_level(0,0)
	platforms.append({ "position": Vector2(320.0, -105.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(0)
	platform.set_stage_and_level(0,0)
	platforms.append({ "position": Vector2(530.0, -220.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(0)
	platform.set_stage_and_level(0,0)
	platforms.append({ "position": Vector2(30.0, -375.0), "platform": platform })
	return platforms

static func _load_0_1() -> Array:
	var platforms = []
	var platform = Platform.instance()
	platform.changeGemType(1)
	platform.set_stage_and_level(0,1)
	platforms.append({ "position": Vector2(350.0, 1200.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(1)
	platform.set_stage_and_level(0,1)
	platforms.append({ "position": Vector2(200.0, 1000.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(1)
	platform.set_stage_and_level(0,1)
	platforms.append({ "position": Vector2(300.0, 730.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(1)
	platform.set_stage_and_level(0,1)
	platforms.append({ "position": Vector2(120.0, 520.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(1)
	platform.set_stage_and_level(0,1)
	platforms.append({ "position": Vector2(480.0, 400.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(1)
	platform.set_stage_and_level(0,1)
	platforms.append({ "position": Vector2(90.0, 200.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(1)
	platform.set_stage_and_level(0,1)
	platforms.append({ "position": Vector2(690.0, 105.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(1)
	platform.set_stage_and_level(0,1)
	platforms.append({ "position": Vector2(90.0, -99.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(1)
	platform.set_stage_and_level(0,1)
	platforms.append({ "position": Vector2(320.0, -105.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(1)
	platform.set_stage_and_level(0,1)
	platforms.append({ "position": Vector2(120.0, -200.0), "platform": platform })
	return platforms


static func _load_0_2() -> Array:
	var platforms = []
	var platform = Platform.instance()
	platform.changeGemType(2)
	platform.set_stage_and_level(0,2)
	platforms.append({ "position": Vector2(350.0, 1200.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(2)
	platform.set_stage_and_level(0,2)
	platforms.append({ "position": Vector2(200.0, 1000.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(2)
	platform.set_stage_and_level(0,2)
	platforms.append({ "position": Vector2(300.0, 730.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(2)
	platform.set_stage_and_level(0,2)
	platforms.append({ "position": Vector2(120.0, 520.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(2)
	platform.set_stage_and_level(0,2)
	platforms.append({ "position": Vector2(480.0, 400.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(2)
	platform.set_stage_and_level(0,2)
	platforms.append({ "position": Vector2(90.0, 200.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(2)
	platform.set_stage_and_level(0,2)
	platforms.append({ "position": Vector2(690.0, 105.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(2)
	platform.set_stage_and_level(0,2)
	platforms.append({ "position": Vector2(90.0, -99.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(2)
	platform.set_stage_and_level(0,2)
	platforms.append({ "position": Vector2(320.0, -105.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(2)
	platform.set_stage_and_level(0,2)
	platforms.append({ "position": Vector2(120.0, -200.0), "platform": platform })
	return platforms

static func _load_0_3() -> Array:
	var platforms = []
	var platform = Platform.instance()
	platform.changeGemType(3)
	platform.set_stage_and_level(0,3)
	platforms.append({ "position": Vector2(350.0, 1200.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(3)
	platform.set_stage_and_level(0,3)
	platforms.append({ "position": Vector2(200.0, 1000.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(3)
	platform.set_stage_and_level(0,3)
	platforms.append({ "position": Vector2(300.0, 730.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(3)
	platform.set_stage_and_level(0,3)
	platforms.append({ "position": Vector2(120.0, 520.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(3)
	platform.set_stage_and_level(0,3)
	platforms.append({ "position": Vector2(480.0, 400.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(3)
	platform.set_stage_and_level(0,3)
	platforms.append({ "position": Vector2(90.0, 200.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(3)
	platform.set_stage_and_level(0,3)
	platforms.append({ "position": Vector2(690.0, 105.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(3)
	platform.set_stage_and_level(0,3)
	platforms.append({ "position": Vector2(90.0, -99.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(3)
	platform.set_stage_and_level(0,3)
	platforms.append({ "position": Vector2(320.0, -105.0), "platform": platform })
	platform = Platform.instance()
	platform.changeGemType(3)
	platform.set_stage_and_level(0,3)
	platforms.append({ "position": Vector2(120.0, -200.0), "platform": platform })
	return platforms